name: Browser compatibility (Firefox and Safari)

on:
  schedule:
    # At the end of every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      repo:
        description: 'blocksuite repository to use'
        required: true
        type: string
        default: 'toeverything/blocksuite'
      ref:
        description: 'blocksuite branch to use'
        required: true
        type: string
        default: 'master'
jobs:
  main-test:
    name: Playground E2E test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browsers: [firefox, webkit]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo || github.repository }}
          ref: ${{ inputs.ref || github.ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Playground
        run: pnpm run build:playground

      - name: Build Playground
        run: pnpm run build:playground

      - name: Install playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browsers }}

      - name: Run playwright tests
        env:
          BROWSER: ${{ matrix.browsers }}
        run: pnpm test -- --forbid-only

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-main
          path: ./test-results
          if-no-files-found: ignore
