name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.husky'
      - '.vscode'
      - '**.md'
      - 'scripts/**'
      - 'packages/react/examples/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.husky'
      - '.vscode'
      - '**.md'
      - 'scripts/**'
      - 'packages/react/examples/**'

jobs:
  build-next:
    name: Build Next.js Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Next.js Example
        run: pnpm run build
        working-directory: packages/react/examples/next

  build-playground:
    name: Build Playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Playground
        run: pnpm run build:playground
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: playground-artifact
          path: ./packages/playground/dist

  e2e-test:
    name: Playground E2E test
    runs-on: ubuntu-latest
    needs:
      - build-playground
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: playground-artifact
          path: ./packages/playground/dist

      - name: Install playwright browsers
        run: npx playwright install chromium

      - name: Run playwright tests
        run: pnpm test -- --forbid-only
        env:
          COVERAGE: true

      - name: Collect code coverage report
        run: pnpm exec nyc report -t .nyc_output --reporter=lcov

      - name: Upload e2e test coverage results
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage/lcov.info
          flags: e2etest
          name: blocksuite
          fail_ci_if_error: true

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-main
          path: ./test-results
          if-no-files-found: ignore

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test:unit:coverage

      - name: Upload unit test coverage results
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage/global/lcov.info,./.coverage/store/lcov.info
          flags: unittest
          name: blocksuite
          fail_ci_if_error: true

  benchmark:
    permissions: write-all
    name: Benchmark
    runs-on: ubuntu-latest
    needs:
      - build-playground
    env:
      CPU_BENCHMARK: true
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: playground-artifact
          path: ./packages/playground/dist

      - name: Install playwright browsers
        run: npx playwright install chromium

      - name: Run Benchmark (yDoc bin size)
        run: pnpm benchmark

      - name: Read size benchmark
        id: bin-size-report
        run: cat bench-mark-size.out >> $GITHUB_OUTPUT

      - name: Report on the pull_request
        uses: thollander/actions-comment-pull-request@v2
        with:
          mode: recreate
          message: |
            | yDoc Bin Size Benchmark | Bytes |
            | --- | --- |
            | BIN Size | ${{ steps.bin-size-report.outputs.BIN_SIZE }} |
            | JSON Size | ${{ steps.bin-size-report.outputs.JSON_SIZE }} |
            | Bin / JSON ratio | ${{ steps.bin-size-report.outputs.RATIO }}% |
          comment_tag: benchmark
